development:
  adapter: postgresql
  encoding: utf8
  database: ecomerce-demo-app_development
  pool: 5
  username: postgres
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: ecomerce-demo-app_test
  pool: 5
  username: postgres
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: ecomerce-demo-app_production
  pool: 5
  username: postgres
  password: root
  host: localhost

